# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Contact the US Government' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Contact the US Government
  pod 'Alamofire'
  pod 'SwiftyJSON'

end
